In [117]:
print("hello")

hello


In [118]:
# eco sales anal.

import numpy as np

# note:- because no up and down 0 | 1000
np.set_printoptions(suppress=True)

sales = np.array([
    [1001, 101, 2, 500, 10, 4.5, 3], # order_id,product_id,quantity,price,discount,rating,delivery_day
    [1002, 102, 1, 1200, 5, 4.2, 5],
    [1003, 103, 4, 250, 0, 4.8, 2],
    [1004, 104, 3, 800, 15, 3.9, 7],
    [1005, 105, 5, 150, 10, 4.1, 4],
    [1006, 101, 2, 500, 20, 4.6, 3],
    [1007, 106, 1, 2500, 5, 4.9, 2],
    [1008, 103, 3, 250, 0, 3.8, 8],
    [1009, 107, 2, 1800, 10, 4.7, 4],
    [1010, 108, 6, 300, 15, 3.5, 6],
    [1011, 105, 3, 150, 5, 4.3, 3],
    [1012, 109, 1, 3500, 20, 4.9, 2],
    [1013, 110, 4, 450, 10, 4.0, 5],
    [1014, 106, 2, 2500, 15, 4.8, 3],
    [1015, 108, 5, 300, 0, 3.2, 9]
])
print(sales)

[[1001.   101.     2.   500.    10.     4.5    3. ]
 [1002.   102.     1.  1200.     5.     4.2    5. ]
 [1003.   103.     4.   250.     0.     4.8    2. ]
 [1004.   104.     3.   800.    15.     3.9    7. ]
 [1005.   105.     5.   150.    10.     4.1    4. ]
 [1006.   101.     2.   500.    20.     4.6    3. ]
 [1007.   106.     1.  2500.     5.     4.9    2. ]
 [1008.   103.     3.   250.     0.     3.8    8. ]
 [1009.   107.     2.  1800.    10.     4.7    4. ]
 [1010.   108.     6.   300.    15.     3.5    6. ]
 [1011.   105.     3.   150.     5.     4.3    3. ]
 [1012.   109.     1.  3500.    20.     4.9    2. ]
 [1013.   110.     4.   450.    10.     4.     5. ]
 [1014.   106.     2.  2500.    15.     4.8    3. ]
 [1015.   108.     5.   300.     0.     3.2    9. ]]


In [119]:
# shape,size , dimensions, number of rows|orders , number of columns
print(sales.shape)
print(sales.size)
print(sales.ndim)

t = sales.shape
print("rows",t[0])
print("columns",t[1])

print(len(sales))
print(len(sales[0]))

(15, 7)
105
2
rows 15
columns 7
15
7


In [120]:
# extract quantity -> reshape(-1,1)
quantity = sales[:,2]
print(quantity)

[2. 1. 4. 3. 5. 2. 1. 3. 2. 6. 3. 1. 4. 2. 5.]


In [121]:
# First 5 orders
print(sales[:5]) # print(sales[0:5])

[[1001.   101.     2.   500.    10.     4.5    3. ]
 [1002.   102.     1.  1200.     5.     4.2    5. ]
 [1003.   103.     4.   250.     0.     4.8    2. ]
 [1004.   104.     3.   800.    15.     3.9    7. ]
 [1005.   105.     5.   150.    10.     4.1    4. ]]


In [122]:
# Last 3 orders
print(sales[-3:])

[[1013.   110.     4.   450.    10.     4.     5. ]
 [1014.   106.     2.  2500.    15.     4.8    3. ]
 [1015.   108.     5.   300.     0.     3.2    9. ]]


In [123]:
# calculate gross amount (quantity * price)
quantity = sales[:,2]
price = sales[:,3]

gross = quantity * price

print(gross)

[1000. 1200. 1000. 2400.  750. 1000. 2500.  750. 3600. 1800.  450. 3500.
 1800. 5000. 1500.]


In [124]:
# calculate discount amount -> (gross * discount)/100
discount = sales[:,4]

quantity = sales[:,2]
price = sales[:,3]

gross = quantity * price

discount_amt = gross * discount / 100

print(discount_amt)

[100.   60.    0.  360.   75.  200.  125.    0.  360.  270.   22.5 700.
 180.  750.    0. ]


In [125]:
# calculate final revenue -> (gross - discount_amt)
rev = gross - discount_amt

print(rev)

[ 900.  1140.  1000.  2040.   675.   800.  2375.   750.  3240.  1530.
  427.5 2800.  1620.  4250.  1500. ]


In [126]:
# total revenue -> np.sum
print(np.sum(rev))

25047.5


In [127]:
# average order revenue -> np.mean
print(np.mean(rev))

1669.8333333333333


In [128]:
# highest revenue
print(np.max(rev))

4250.0


In [129]:
# lowest revenue
print(np.min(rev))

427.5


In [130]:
# total quantity sold
print(np.sum(quantity))

44.0


In [131]:
# find higly rated orders -> >= 4.5 --> fancy indexing | boolean indexing
rating = sales[:,5]

result = sales[rating >= 4.5]

print(result)
print(np.mean(rating))

[[1001.   101.     2.   500.    10.     4.5    3. ]
 [1003.   103.     4.   250.     0.     4.8    2. ]
 [1006.   101.     2.   500.    20.     4.6    3. ]
 [1007.   106.     1.  2500.     5.     4.9    2. ]
 [1009.   107.     2.  1800.    10.     4.7    4. ]
 [1012.   109.     1.  3500.    20.     4.9    2. ]
 [1014.   106.     2.  2500.    15.     4.8    3. ]]
4.279999999999999


In [132]:
# discount_amt -> gross * discount/100
# gross -> ( quantity * price )
# revenue -> (gross - disount_amt)

# revenue -> sort -> asc | desc

gross = sales[:,6] * sales[:,3]

discount_amt = gross * sales[:,4]/100

rev = gross - discount_amt
print(rev)
print(np.sort(rev))
print(np.sort(rev)[::-1])

[1350.  5700.   500.  4760.   540.  1200.  4750.  2000.  6480.  1530.
  427.5 5600.  2025.  6375.  2700. ]
[ 427.5  500.   540.  1200.  1350.  1530.  2000.  2025.  2700.  4750.
 4760.  5600.  5700.  6375.  6480. ]
[6480.  6375.  5700.  5600.  4760.  4750.  2700.  2025.  2000.  1530.
 1350.  1200.   540.   500.   427.5]


In [133]:
# add new order | row -> vstack()
new_order = np.array([1016,111,2,600,10,4.6,5])

sales = np.vstack((sales,new_order))
print(sales)

[[1001.   101.     2.   500.    10.     4.5    3. ]
 [1002.   102.     1.  1200.     5.     4.2    5. ]
 [1003.   103.     4.   250.     0.     4.8    2. ]
 [1004.   104.     3.   800.    15.     3.9    7. ]
 [1005.   105.     5.   150.    10.     4.1    4. ]
 [1006.   101.     2.   500.    20.     4.6    3. ]
 [1007.   106.     1.  2500.     5.     4.9    2. ]
 [1008.   103.     3.   250.     0.     3.8    8. ]
 [1009.   107.     2.  1800.    10.     4.7    4. ]
 [1010.   108.     6.   300.    15.     3.5    6. ]
 [1011.   105.     3.   150.     5.     4.3    3. ]
 [1012.   109.     1.  3500.    20.     4.9    2. ]
 [1013.   110.     4.   450.    10.     4.     5. ]
 [1014.   106.     2.  2500.    15.     4.8    3. ]
 [1015.   108.     5.   300.     0.     3.2    9. ]
 [1016.   111.     2.   600.    10.     4.6    5. ]]


In [137]:
# # # # add new column -> gross -> hstack()
gross = sales[:,2] * sales[:,3]

sales = np.hstack((sales,gross.reshape(-1,1)))
print(sales)

[[1001.   101.     2.   500.    10.     4.5    3.  1000. ]
 [1002.   102.     1.  1200.     5.     4.2    5.  1200. ]
 [1003.   103.     4.   250.     0.     4.8    2.  1000. ]
 [1004.   104.     3.   800.    15.     3.9    7.  2400. ]
 [1005.   105.     5.   150.    10.     4.1    4.   750. ]
 [1006.   101.     2.   500.    20.     4.6    3.  1000. ]
 [1007.   106.     1.  2500.     5.     4.9    2.  2500. ]
 [1008.   103.     3.   250.     0.     3.8    8.   750. ]
 [1009.   107.     2.  1800.    10.     4.7    4.  3600. ]
 [1010.   108.     6.   300.    15.     3.5    6.  1800. ]
 [1011.   105.     3.   150.     5.     4.3    3.   450. ]
 [1012.   109.     1.  3500.    20.     4.9    2.  3500. ]
 [1013.   110.     4.   450.    10.     4.     5.  1800. ]
 [1014.   106.     2.  2500.    15.     4.8    3.  5000. ]
 [1015.   108.     5.   300.     0.     3.2    9.  1500. ]
 [1016.   111.     2.   600.    10.     4.6    5.  1200. ]]


In [139]:
# # add new column -> revenue -> hstack()
gross = sales[:,2] * sales[:,3]
discount_amt = gross * sales[:,4]/100
rev = gross - discount_amt
sales = np.hstack((sales,rev.reshape(-1,1)))

print(sales)

[[1001.   101.     2.   500.    10.     4.5    3.  1000.   900. ]
 [1002.   102.     1.  1200.     5.     4.2    5.  1200.  1140. ]
 [1003.   103.     4.   250.     0.     4.8    2.  1000.  1000. ]
 [1004.   104.     3.   800.    15.     3.9    7.  2400.  2040. ]
 [1005.   105.     5.   150.    10.     4.1    4.   750.   675. ]
 [1006.   101.     2.   500.    20.     4.6    3.  1000.   800. ]
 [1007.   106.     1.  2500.     5.     4.9    2.  2500.  2375. ]
 [1008.   103.     3.   250.     0.     3.8    8.   750.   750. ]
 [1009.   107.     2.  1800.    10.     4.7    4.  3600.  3240. ]
 [1010.   108.     6.   300.    15.     3.5    6.  1800.  1530. ]
 [1011.   105.     3.   150.     5.     4.3    3.   450.   427.5]
 [1012.   109.     1.  3500.    20.     4.9    2.  3500.  2800. ]
 [1013.   110.     4.   450.    10.     4.     5.  1800.  1620. ]
 [1014.   106.     2.  2500.    15.     4.8    3.  5000.  4250. ]
 [1015.   108.     5.   300.     0.     3.2    9.  1500.  1500. ]
 [1016.   

In [140]:
# delete rating column
sales = np.delete(sales,5,axis=1)
print(sales)

[[1001.   101.     2.   500.    10.     3.  1000.   900. ]
 [1002.   102.     1.  1200.     5.     5.  1200.  1140. ]
 [1003.   103.     4.   250.     0.     2.  1000.  1000. ]
 [1004.   104.     3.   800.    15.     7.  2400.  2040. ]
 [1005.   105.     5.   150.    10.     4.   750.   675. ]
 [1006.   101.     2.   500.    20.     3.  1000.   800. ]
 [1007.   106.     1.  2500.     5.     2.  2500.  2375. ]
 [1008.   103.     3.   250.     0.     8.   750.   750. ]
 [1009.   107.     2.  1800.    10.     4.  3600.  3240. ]
 [1010.   108.     6.   300.    15.     6.  1800.  1530. ]
 [1011.   105.     3.   150.     5.     3.   450.   427.5]
 [1012.   109.     1.  3500.    20.     2.  3500.  2800. ]
 [1013.   110.     4.   450.    10.     5.  1800.  1620. ]
 [1014.   106.     2.  2500.    15.     3.  5000.  4250. ]
 [1015.   108.     5.   300.     0.     9.  1500.  1500. ]
 [1016.   111.     2.   600.    10.     5.  1200.  1080. ]]


In [142]:
# delete order -> 1005
result = np.delete(sales,4,axis=0)

print(result)

[[1001.   101.     2.   500.    10.     3.  1000.   900. ]
 [1002.   102.     1.  1200.     5.     5.  1200.  1140. ]
 [1003.   103.     4.   250.     0.     2.  1000.  1000. ]
 [1004.   104.     3.   800.    15.     7.  2400.  2040. ]
 [1006.   101.     2.   500.    20.     3.  1000.   800. ]
 [1007.   106.     1.  2500.     5.     2.  2500.  2375. ]
 [1008.   103.     3.   250.     0.     8.   750.   750. ]
 [1009.   107.     2.  1800.    10.     4.  3600.  3240. ]
 [1010.   108.     6.   300.    15.     6.  1800.  1530. ]
 [1011.   105.     3.   150.     5.     3.   450.   427.5]
 [1012.   109.     1.  3500.    20.     2.  3500.  2800. ]
 [1013.   110.     4.   450.    10.     5.  1800.  1620. ]
 [1014.   106.     2.  2500.    15.     3.  5000.  4250. ]
 [1015.   108.     5.   300.     0.     9.  1500.  1500. ]
 [1016.   111.     2.   600.    10.     5.  1200.  1080. ]]


In [144]:
# [2,5]-> nan | [7,5] -> nan
sales_missing = sales.copy()

sales_missing[2,5] = np.nan
sales_missing[7,5] = np.nan

print(sales_missing)

[[1001.   101.     2.   500.    10.     3.  1000.   900. ]
 [1002.   102.     1.  1200.     5.     5.  1200.  1140. ]
 [1003.   103.     4.   250.     0.     nan 1000.  1000. ]
 [1004.   104.     3.   800.    15.     7.  2400.  2040. ]
 [1005.   105.     5.   150.    10.     4.   750.   675. ]
 [1006.   101.     2.   500.    20.     3.  1000.   800. ]
 [1007.   106.     1.  2500.     5.     2.  2500.  2375. ]
 [1008.   103.     3.   250.     0.     nan  750.   750. ]
 [1009.   107.     2.  1800.    10.     4.  3600.  3240. ]
 [1010.   108.     6.   300.    15.     6.  1800.  1530. ]
 [1011.   105.     3.   150.     5.     3.   450.   427.5]
 [1012.   109.     1.  3500.    20.     2.  3500.  2800. ]
 [1013.   110.     4.   450.    10.     5.  1800.  1620. ]
 [1014.   106.     2.  2500.    15.     3.  5000.  4250. ]
 [1015.   108.     5.   300.     0.     9.  1500.  1500. ]
 [1016.   111.     2.   600.    10.     5.  1200.  1080. ]]


In [ ]:
# nan -> count | sum | positions ---> sales_missing
