In [ ]:
print("hello")

hello


In [ ]:
# install numpy
!pip install numpy

In [ ]:
# import packages
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
#create list and convert into array
l = [88,29,19,24,84,76]
import numpy as np
arr = np.array(l)
print("list")
print(l)
print(type(l))
print("array | numpy")
print(arr)
print(type(arr))

list
[88, 29, 19, 24, 84, 76]
<class 'list'>
array | numpy
[88 29 19 24 84 76]
<class 'numpy.ndarray'>


In [ ]:
# 1d
arr1 = np.array([10,20,30])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[10 20 30]
1
(3,)


In [ ]:
arr2 = np.array([
      [10,20],[30,40]
    ])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[10 20]
 [30 40]]
2
(2, 2)


In [ ]:
arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [ ]:
import numpy as np
scores = np.array([88,34,76,85,99,80])
# mean , min , max
print("average",scores.mean())
print("min",scores.min())
print("max",scores.max())
print(scores > 60)
print(scores + 2)
print(scores * 2)
print(scores.shape) # ndim
print(scores.dtype)
print(scores.size)

average 77.0
min 34
max 99
[ True False  True  True  True  True]
[ 90  36  78  87 101  82]
[176  68 152 170 198 160]
(6,)
int64
6


In [ ]:
# zeros
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
arr1 = np.ones((3,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr2 = np.ones((2,3,4))
print(arr2)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [4]:
# 1d -> vector
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [5]:
# 2d -> matrix
import numpy as np
arr1 = np.array([
    [70,80,90],
    [60,75,85],
    [88,92,95]
])
print(arr1)

[[70 80 90]
 [60 75 85]
 [88 92 95]]


In [6]:
# 4 students and 3 subjects
import numpy as np
arr1 = np.array([
    [70,80,90],
    [60,75,85],
    [88,92,95],
    [58,42,65]
])
print(arr1)

[[70 80 90]
 [60 75 85]
 [88 92 95]
 [58 42 65]]


In [13]:
# avg marks of each students
avg_marks_students = np.mean(arr1,axis=1) # axis=1 for each row
print("avg marks of each students",np.round(avg_marks_students))

# avg marks of each subjects
avg_marks_subjects = np.mean(arr1,axis=0) # axis=1 for each row
print("avg marks of each subjects",np.round(avg_marks_subjects))


avg marks of each students [80. 73. 92. 55.]
avg marks of each subjects [69. 72. 84.]


In [16]:
# total marks of each students  # (students are in row format that'why we are using axis=1)
student_total = np.sum(arr1,axis=1)
print("total marks of each students",student_total)

# highest mark in each subject # (subjects are in cols format that'why we are using axis=0)
highest_sub_marks = np.max(arr1,axis=0)
print("highest mark in each subject",highest_sub_marks)

total marks of each students [240 220 275 165]
highest mark in each subject [88 92 95]
