In [1]:
print("hello")

hello


In [3]:
# install numpy
!pip install numpy

In [5]:
# import packages
import numpy as np
print(np.__version__)

2.1.3


In [6]:
#create list and convert into array
l = [88,29,19,24,84,76]
import numpy as np
arr = np.array(l)
print("list")
print(l)
print(type(l))
print("array | numpy")
print(arr)
print(type(arr))

list
[88, 29, 19, 24, 84, 76]
<class 'list'>
array | numpy
[88 29 19 24 84 76]
<class 'numpy.ndarray'>


In [21]:
# 1d
arr1 = np.array([10,20,30])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[10 20 30]
1
(3,)


In [22]:
arr2 = np.array([
      [10,20],[30,40]
    ])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[10 20]
 [30 40]]
2
(2, 2)


In [23]:
arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [20]:
import numpy as np
scores = np.array([88,34,76,85,99,80])
# mean , min , max
print("average",scores.mean())
print("min",scores.min())
print("max",scores.max())
print(scores > 60)
print(scores + 2)
print(scores * 2)
print(scores.shape) # ndim
print(scores.dtype)
print(scores.size)

average 77.0
min 34
max 99
[ True False  True  True  True  True]
[ 90  36  78  87 101  82]
[176  68 152 170 198 160]
(6,)
int64
6


In [27]:
# zeros
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [26]:
arr1 = np.zeros((3,4))
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
arr2 = np.zeros((2,3,4))
print(arr2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
