In [ ]:
print("hello")

hello


In [ ]:
# install numpy
!pip install numpy

In [ ]:
# import packages
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
#create list and convert into array
l = [88,29,19,24,84,76]
import numpy as np
arr = np.array(l)
print("list")
print(l)
print(type(l))
print("array | numpy")
print(arr)
print(type(arr))

list
[88, 29, 19, 24, 84, 76]
<class 'list'>
array | numpy
[88 29 19 24 84 76]
<class 'numpy.ndarray'>


In [ ]:
# 1d
arr1 = np.array([10,20,30])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[10 20 30]
1
(3,)


In [ ]:
arr2 = np.array([
      [10,20],[30,40]
    ])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[10 20]
 [30 40]]
2
(2, 2)


In [ ]:
arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [ ]:
import numpy as np
scores = np.array([88,34,76,85,99,80])
# mean , min , max
print("average",scores.mean())
print("min",scores.min())
print("max",scores.max())
print(scores > 60)
print(scores + 2)
print(scores * 2)
print(scores.shape) # ndim
print(scores.dtype)
print(scores.size)

average 77.0
min 34
max 99
[ True False  True  True  True  True]
[ 90  36  78  87 101  82]
[176  68 152 170 198 160]
(6,)
int64
6


In [ ]:
# zeros
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
arr1 = np.ones((3,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr2 = np.ones((2,3,4))
print(arr2)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# 1d -> vector
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

# element 1 and 2 access by the help of indexing


[10 20 30 40 50]


In [ ]:
# 2d -> matrix
import numpy as np
arr1 = np.array([
    [70,80,90],
    [60,75,85],
    [88,92,95]
])
print(arr1)

[[70 80 90]
 [60 75 85]
 [88 92 95]]


In [ ]:
# 4 students and 3 subjects
import numpy as np
arr1 = np.array([
    [70,80,90],
    [60,75,85],
    [88,92,95],
    [58,42,65]
])
print(arr1)
print(arr1[0,1]) # row 0, cols 1

[[70 80 90]
 [60 75 85]
 [88 92 95]
 [58 42 65]]
80


In [ ]:
# avg marks of each students
avg_marks_students = np.mean(arr1,axis=1) # axis=1 for each row
print("avg marks of each students",np.round(avg_marks_students))

# avg marks of each subjects
avg_marks_subjects = np.mean(arr1,axis=0) # axis=1 for each row
print("avg marks of each subjects",np.round(avg_marks_subjects))


avg marks of each students [80. 73. 92. 55.]
avg marks of each subjects [69. 72. 84.]


In [ ]:
# total marks of each students  # (students are in row format that'why we are using axis=1)
student_total = np.sum(arr1,axis=1)
print("total marks of each students",student_total)

# highest mark in each subject # (subjects are in cols format that'why we are using axis=0)
highest_sub_marks = np.max(arr1,axis=0)
print("highest mark in each subject",highest_sub_marks)

total marks of each students [240 220 275 165]
highest mark in each subject [88 92 95]


In [ ]:
#Array Properties (shape, size, ndim, dtype) # 1D or 2D
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60]
],dtype=np.float16)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
float16


In [ ]:
# reshape array and arange
import numpy as np
arr = np.arange(1,10)
print(arr)
# for i in range(1,5):
#   print(i)

[1 2 3 4 5 6 7 8 9]
1
2
3
4


In [ ]:
arr1 = np.arange(6)
print(arr1)
arr_reshape = arr1.reshape(3,2) #
print(arr_reshape)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
arr2 = np.arange(12).reshape(4,3)
print(arr2)
# alternative
arr2 = np.arange(12).reshape(-1,3) # 12/2 -> (6,2) | 12/3 -> (4,3)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#note:- flatten and reval -> use to convert any array to 1d array
arr = np.array([
    [10,20],
    [30,40]
])
print(arr)
print(arr.reshape(-1)) # convert into 1d

[[10 20]
 [30 40]]
[10 20 30 40]


In [ ]:
# 1d -> 3d
arr = np.arange(24).reshape(2,3,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# indexing
arr1 = np.arange(6).reshape(3,2)
print(arr1)
print(arr1[1,1]) # first value for row and second for cols
print(arr1[1][1]) # first for row and second for cols

[[0 1]
 [2 3]
 [4 5]]
3
3


In [ ]:
# sorting
arr = np.array([10,3,15,20])
print(arr)
print(np.sort(arr)) # ascending order
print(np.sort(arr)[::-1]) # decending order

[10  3 15 20]
[ 3 10 15 20]
[20 15 10  3]


In [5]:
# sorting 2d array
import numpy as np
arr2 = np.array([
    [3,2,1],
    [6,5,7]
])
print(np.sort(arr2)) # by default row wise
print(np.sort(arr2,axis=0)) # column wise sort

[[1 2 3]
 [5 6 7]]
[[3 2 1]
 [6 5 7]]


In [7]:
# filtering in numpy
arr = np.array([10,20,25,15,40])
print(arr[arr > 20])
print(arr[arr%2 == 0]) # even numbers

[25 40]
[10 20 40]


In [10]:
# Dynamic array means: values come at runtime (from user, loop, file, etc.).
import numpy as np
n = int(input("Enter size: "))
arr = []
for i in range(n):
  val = int(input("Enter value: "))
  arr.append(val)

np_arr = np.array(arr)
print(np_arr)
print(type(np_arr))

Enter size: 3
Enter value: 11
Enter value: 9
Enter value: 10
[11  9 10]
<class 'numpy.ndarray'>


In [13]:
# Using zeros(), ones(), arange(), linspace() , full() , fill() -> random data generate
import numpy as np
arr = np.zeros(5)
print(arr)

arr1 = np.zeros((3,2))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [22]:
arr1 = np.full(5,7) # 5 -> 7
print(arr1)

arr2 = np.full(5,1)
print(arr2)

arr_2d = np.full((2,3),5)
print(arr_2d)

[7 7 7 7 7]
[1 1 1 1 1]
[[5 5 5]
 [5 5 5]]


In [20]:
arr3 = np.zeros((3,2))
arr3.fill(9)
print(arr3)

[[9. 9.]
 [9. 9.]
 [9. 9.]]


In [24]:
d = np.arange(1,10,1)
print(d)

[1 2 3 4 5 6 7 8 9]


In [31]:
e = np.linspace(1,6,4)
print(e)

[1.         2.66666667 4.33333333 6.        ]
