In [1]:
print("helo")

helo


In [ ]:
import numpy as np
list_1d = [10,20,30,40]
vec = np.array(list_1d)
print(vec)
print(vec.dtype)

# dtype
vec = np.array(list_1d,dtype=np.float16)
print(vec)
print(vec.dtype)

[10 20 30 40]
int64
[10. 20. 30. 40.]
float16


In [ ]:
list_2d = [
    [1,2,3],
    [4,5,6]
]
mat = np.array(list_2d)
print(mat)
print(mat.dtype)

# dtype
mat = np.array(list_2d,dtype=np.float16)
print(mat)
print(mat.dtype)

[[1 2 3]
 [4 5 6]]
int64
[[1. 2. 3.]
 [4. 5. 6.]]
float16


In [ ]:
# Problem: How do you initialize a 3×4 integer matrix populated entirely with zeros?
import numpy as np
zero_mat = np.zeros((3,4),dtype=int)
print(zero_mat)
print("shape",zero_mat.shape)
print("dtype",zero_mat.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape (3, 4)
dtype int64


In [ ]:
# Problem: How do you create a 3D tensor of shape (2, 3, 2) filled with ones?
import numpy as np
ones_tensor = np.ones((2,3,2),dtype=np.float32)
print(ones_tensor)
print("tensor shape",ones_tensor.shape)
print("data type", ones_tensor.dtype)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
tensor shape (2, 3, 2)
data type float32


In [ ]:
# Problem: How do you construct a 3×3 matrix where every element is set to 7.5 ?
import numpy as np
cont_mat = np.full(shape=(3,3),fill_value=7.5)
print(cont_mat)

[[7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]]


In [ ]:
# Problem: How does the arr.fill() method differ from np.full(), and how is it used to mutate an existing pre-allocated array?
import numpy as np
buf = np.empty((2,3),dtype=np.int32)
print(buf)

# Overwrite all values in-place without new memory allocation
buf.fill(99)
print(buf)

[[         0          0          0]
 [1071644672          0 1072693248]]
[[99 99 99]
 [99 99 99]]


In [ ]:
# Problem: How do you generate an array of numbers from 10 to 50 with a step of 5,
# and an array with floating-point increments from 0.0 to 1.0 with a step of 0.2?

import numpy as np
int_seq = np.arange(10,50,5) # start,stop,step
print(int_seq)

float_seq = np.arange(0.0 , 1.0 , 0.2) #
print(float_seq)

[10 15 20 25 30 35 40 45]
[0.  0.2 0.4 0.6 0.8]


In [ ]:
# Problem: How do you generate exactly 5 linearly spaced values between 0 and 100 (inclusive)?
import numpy as np
val = np.linspace(0,100,5)
print(val)

# (stop - start)/ num - 1

# ( 100-0 ) / 5 -1
# 100/4 = 25


[  0.  25.  50.  75. 100.]


In [ ]:
# Problem: Write code that creates a 1D vector, a 2D matrix, and a 3D tensor, and display their structures.
import numpy as np
vec = np.array([1,2,3])
mat = np.array([[1,2,3],[4,5,6]])
ten = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(vec)
print(mat)
print(ten)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Array Properties (shape, size, ndim, dtype) # 1D or 2D and 3D
import numpy as np
vec = np.array([1,2,3])
mat = np.array([[1,2,3],[4,5,6]])
ten = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print("shape",vec.shape)
print(mat.shape)
print(ten.shape)

print("size",vec.size)
print(mat.size)
print(ten.size)

print("ndim",vec.ndim)
print(mat.ndim)
print(ten.ndim)

shape (3,)
(2, 3)
(2, 2, 2)
size 3
6
8
ndim 1
2
3


In [ ]:
# Problem: Given a 2D array of shape (3, 5), what do len(arr) and arr.size return?
import numpy as np
val = np.ones((3,5))
print(val)
print(len(val)) # no. of rows
print(len(val[0])) # no. of cols

print(val.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
3
5
15


In [ ]:
# indexing and slicing
# 1d array
# indexing is always start from zero and position is always start from one
import numpy as np
marks = np.array([70,80,90,85])
print(marks)
print(marks[0]) # 70
print(marks[2]) # 90
print(marks[-1]) # negative one for last value

[70 80 90 85]
70
90
85


In [ ]:
# 2d array indexing
import numpy as np
students = np.array([
    [70,80,90],
    [65,75,85]
])
print(students)
# print(students[rows][cols])
print("row 0 = ",students[0])
print("row 0 and cols 0 = ",students[0][0])

[[70 80 90]
 [65 75 85]]
row 0 =  [70 80 90]
row 0 and cols 0 =  70


In [ ]:
# question
import numpy as np
n =  int(input("Enter number of students:"))
names = []
marks = []

for i in range(n):
  name = input("Enter Student name:")
  mark = int(input("Enter marks:"))

  names.append(name)
  marks.append(mark)

# convert list in numpy array
names_array = np.array(names)
marks_array = np.array(marks)
print("Names:", names_array)
print("Marks:", marks_array)

Enter number of students:3
Enter Student name:nitin
Enter marks:70
Enter Student name:priyansh
Enter marks:80
Enter Student name:raj
Enter marks:85
Names: ['nitin' 'priyansh' 'raj']
Marks: [70 80 85]


In [ ]:
# slicing
# 1d array
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr)
print("slicing",arr[1:3]) # starting index : end index (last value exclude)

[10 20 30 40 50 60]
slicing [20 30]


In [ ]:
# basic slicing concepts | shallow copy
# note:- if you update slicing array then your original array also will changed
arr1 = np.array([5,6,7,9,11,2])
print(arr1)
arr1_slice = arr1[1:4]
print(arr1_slice)
print("before update index 0 of slice = ",arr1_slice[0])
arr1_slice[0] =  20
print("after update index 0 of slice = ",arr1_slice[0])

print("original array =", arr1)

[ 5  6  7  9 11  2]
[6 7 9]
before update index 0 of slice =  6
after update index 0 of slice =  20
original array = [ 5 20  7  9 11  2]


In [ ]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[1:4] # last number always exclude
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[6 7 8]


In [ ]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[:4] # default starting from zero index
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[5 6 7 8]


In [ ]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[2:] # default last index number
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[7 8 2 3]


In [ ]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[:] # default start from 0 and last index
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[5 6 7 8 2 3]


In [ ]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[1:4:2] #  start from 1 and end with 3 and step by 1
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[6 8]


In [ ]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[::2] #  start from 0 and end with last and step by 1
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[5 7 2]


In [ ]:
# 1d example reverse
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[::-1] #  start from 0 and end with last and step by -1
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[3 2 8 7 6 5]


In [ ]:
# 1d example basic
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
print(arr1)
arr1_slice = arr1[1:4]
print("before update=",arr1_slice)

# update slice array
arr1_slice[0] = 21
print("after update=",arr1_slice)

print("original array",arr1) #

[5 6 7 8 2 3]
before update= [6 7 8]
after update= [21  7  8]
original array [ 5 21  7  8  2  3]


In [ ]:
# fancy indexing for 1d | deep copy
# note:- its create a new array instead of changes in original one
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
print(arr1)
arr1_slice = arr1[[1,2,3]] # fancy indexing
print("before update=",arr1_slice)

# update slice array
arr1_slice[0] = 21
print("after update=",arr1_slice)

print("original array",arr1) #

[5 6 7 8 2 3]
before update= [6 7 8]
after update= [21  7  8]
original array [5 6 7 8 2 3]


In [ ]:
# boolean indexing
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
print(arr1)
arr1_slice = arr1[arr1 > 5] # boolean indexing
print("before update=",arr1_slice)

# update slice array
arr1_slice[0] = 21
print("after update=",arr1_slice)

print("original array",arr1) #

[5 6 7 8 2 3]
before update= [6 7 8]
after update= [21  7  8]
original array [5 6 7 8 2 3]


In [ ]:
# slicing in 2d array
import numpy as np
students = np.array([
    [70,80,90],
    [65,75,85],
    [60,70,80]
])
print(students)
# slicing in 2d
print("indexing example",students[0,1]) # row and cols
print("slicing example",students[0:2,1:3]) # row and cols

[[70 80 90]
 [65 75 85]
 [60 70 80]]
indexing example 80
slicing example [[80 90]
 [75 85]]


In [ ]:
# array reshape
# reshape
# flatten()
# reval()
# transpose

In [ ]:
import numpy as np
arr = np.arange(12)
print(arr)

# reshape 2d
arr1 = np.arange(12) # 3*4 | 4*3 | 6*2 | 2*6  (rows,cols)
res_arr1 = np.reshape(arr1,(3,4))
print(res_arr1)

# reshape 3d
arr2 = np.arange(24) # 3*2*4 | 4*2*3 |
res_arr2 = np.reshape(arr2,(3,2,4))
print(res_arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# flatten | create copy then works
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)

# 2d -> 1d
flat_arr = arr.flatten()
flat_arr[0] = 100
print(flat_arr)
print(arr)

# 3d -> 1d
arr1 = np.arange(24).reshape(3,4,2)
print(arr1)
flat_arr1 = arr1.flatten()
print(flat_arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[100   1   2   3   4   5   6   7   8   9  10  11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# ravel | work on original array
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)

# 2d -> 1d
flat_arr = arr.ravel()
flat_arr[0] = 100
print(flat_arr)
print("updated array:",arr)

# 3d -> 1d


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[100   1   2   3   4   5   6   7   8   9  10  11]
updated array: [[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [ ]:
# transpose
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
trans_arr = arr.T # .transpose()
print(trans_arr) # 4 X 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
import numpy as np
arr = np.arange(5)
print(arr)

# increase size
res_arr = np.resize(arr,(8,))
print(res_arr)

[0 1 2 3 4]
[0 1 2 3 4 0 1 2]


In [ ]:
# looping with numpy
# for
# while
import numpy as np
arr = np.array([10,20,30,40,50])
i = 0
while i < len(arr):
  print(arr[i])
  i += 1
print("for loop:-")
for i in arr:
  print(i)

10
20
30
40
50
for loop:-
10
20
30
40
50


In [ ]:
# np.where
import numpy as np
# 1d
arr = np.array([10,3,4,80,90,6,7])
print(arr)

# np.where
arr_w = np.where(arr>20,"True","False") # (condition)?"True":"False"
print(arr_w)

[10  3  4 80 90  6  7]
['False' 'False' 'False' 'True' 'True' 'False' 'False']


In [ ]:
# updated array
arr1 = np.array([10,3,4,80,90,6,7])
print(arr1)

# np.where
result1 = arr1[np.where(arr1>20)] # arr1
print(result1)

[10  3  4 80 90  6  7]
[80 90]


In [ ]:
import numpy as np
arr = np.array([11,20,22,40,45,60])
print(arr)

# even index
even_index = np.where(arr % 2 == 0)
print(even_index)

# value
even_value = arr[np.where(arr % 2 == 0)]
print(even_value)


[11 20 22 40 45 60]
(array([1, 2, 3, 5]),)
[20 22 40 60]


In [ ]:
# np.where use as replace
arr = np.array([11,20,22,40,45,60])
print(arr)

# np.where
result = np.where(arr>20,100,0) # (condition)?"True":"False"
print(result)

[11 20 22 40 45 60]
[  0   0 100 100 100 100]


In [ ]:
# np.where for 2d
import numpy as np
arr = np.array([
    [10,20,25],
    [45,50,55],
    [60,20,70]
])
print(arr)

# np.where
result = np.where(arr > 40)
print(result) # index of rows , index of cols
# 1  0 -> 45
# 1  1 -> 50
# 1  2 -> 55
# 2  0 -> 60
# 2  2 -> 70


[[10 20 25]
 [45 50 55]
 [60 20 70]]
(array([1, 1, 1, 2, 2]), array([0, 1, 2, 0, 2]))


In [ ]:
import numpy as np
arr = np.array([
    [10,20,25],
    [45,50,55],
    [60,20,70]
])
print(arr)

# np.where
result = np.where(arr>40)
print(type(result))
print(result[0]) # rows
print(result[1]) # cols

# final value
print(arr[result[0],result[1]])

# np.where | alternative
# rows,cols = np.where(arr > 40)
# print(rows) # rows
# print(cols) # cols

# final value
# print(arr[rows,cols])

[[10 20 25]
 [45 50 55]
 [60 20 70]]
<class 'tuple'>
[1 1 1 2 2]
[0 1 2 0 2]
[45 50 55 60 70]


In [ ]:
import numpy as np
arr = np.array([
    [10,20,25],
    [45,50,55],
    [60,20,70]
])
print(arr)

# condition
result = np.where(arr>=36,"Pass","Fail")
print(result)

[[10 20 25]
 [45 50 55]
 [60 20 70]]
[['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']
 ['Pass' 'Fail' 'Pass']]


In [ ]:
# example of np.where 1d and 2d

In [ ]:
# adding and removing data
# 1. np.concatenate((arr1,arr2))
# 2. np.vstack((original,new_arr)) # add new row
# 3. np.hstack((original,new_arr)) # add new cols
# 4. np.delete(arr,index_no) # delete element by index number

In [ ]:
# np.concatenate
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

# np.concatenate
result = np.concatenate((arr1,arr2))
print(result)

#
result1 = arr1 + arr2
print(result1)

[10 20 30 40 50 60]
[50 70 90]


In [2]:
# 2d array
import numpy as np
arr1 = np.array([
    [10,20],
    [30,40]
])
arr2 = np.array([
    [50,60],
    [70,80]
])
result = np.concatenate((arr1,arr2)) # row - wise
print(result)

result = np.concatenate((arr1,arr2),axis=1) # col - wise
print(result)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 20 50 60]
 [30 40 70 80]]


In [3]:
# add new row for 1d
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

# vstack
result = np.vstack((arr1,arr2))
print(result)

[[10 20 30]
 [40 50 60]]


In [11]:
# add new row for 2d
original = np.array([
    [10,20,30],
    [40,50,60]
])
new_row = np.array([70,80,90])

# alternative of vstack
result = np.concatenate((original,[new_row])) # axis=0
print(result)

# vstack
result = np.vstack((original,new_row))
print(result)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
# hstack -> add new cols
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

result = np.hstack((arr1,arr2))
print(result)

[10 20 30 40 50 60]


In [13]:
# hstack -> for 2d

In [18]:
# np.delete -> delete element | delete row | delete column
import numpy as np
arr = np.array([10,20,30,40,50])

#
result = np.delete(arr,2)
print(result)

# copy | original
print("copy",result)
print("original",arr)

[10 20 40 50]
copy [10 20 40 50]
original [10 20 30 40 50]


In [20]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

result = np.delete(arr,1,axis=0) # 1 -> index | axis=0 for row

print(result)

[[10 20 30]
 [70 80 90]]


In [21]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

result = np.delete(arr,1,axis=1) # 1 -> index | axis=1 for cols

print(result)

[[10 30]
 [40 60]
 [70 90]]


In [23]:
# handle missing values
# np.nan | np.isnan
import numpy as np
arr = np.array([10,20,np.nan,40,np.nan,60]) # null -> nan
print(arr)

#
result = np.isnan(arr)
print(result)

[10. 20. nan 40. nan 60.]
[False False  True False  True False]


In [34]:
import numpy as np
arr = np.array([10,20,np.nan,40,np.nan,60]) # null -> nan
print(arr)

#
index = np.where(np.isnan(arr)) # for index
print(index)

#
value = arr[index] # for value
print(value)

[10. 20. nan 40. nan 60.]
(array([2, 4]),)
[nan nan]


In [36]:
# count number of nan values
import numpy as np
arr = np.array([10,20,np.nan,40,np.nan,60]) # null -> nan
print(arr)

result = np.sum(np.isnan(arr))
print(result)

[10. 20. nan 40. nan 60.]
2


In [38]:
# np.any -> to check any nan value is exist or not
import numpy as np
arr = np.array([10,20,np.nan,40,np.nan,60]) # null -> nan
print(arr)

result = np.any(np.isnan(arr))
print(result)

[10. 20. nan 40. nan 60.]
True


In [39]:
# np.all -> to check all value for nan or not
import numpy as np
arr = np.array([10,20,np.nan,40,np.nan,60]) # null -> nan
print(arr)

result = np.all(np.isnan(arr))
print(result)

[10. 20. nan 40. nan 60.]
False


In [40]:
# handle missing values 2d

In [46]:
# question on sorting

arr = np.array([
    [10,20,13],
    [21,9,15]
])
print(arr)

result = np.sort(arr)[:,::-1] # row wise | axis=0

print(result)

result1 = np.sort(arr,axis=1)[::-1,:] # cols wise | axis=1

print(result1)


[[10 20 13]
 [21  9 15]]
[[20 13 10]
 [21 15  9]]
