In [1]:
print("helo")

helo


In [2]:
import numpy as np
list_1d = [10,20,30,40]
vec = np.array(list_1d)
print(vec)
print(vec.dtype)

# dtype
vec = np.array(list_1d,dtype=np.float16)
print(vec)
print(vec.dtype)

[10 20 30 40]
int64
[10. 20. 30. 40.]
float16


In [3]:
list_2d = [
    [1,2,3],
    [4,5,6]
]
mat = np.array(list_2d)
print(mat)
print(mat.dtype)

# dtype
mat = np.array(list_2d,dtype=np.float16)
print(mat)
print(mat.dtype)

[[1 2 3]
 [4 5 6]]
int64
[[1. 2. 3.]
 [4. 5. 6.]]
float16


In [4]:
# Problem: How do you initialize a 3×4 integer matrix populated entirely with zeros?
import numpy as np
zero_mat = np.zeros((3,4),dtype=int)
print(zero_mat)
print("shape",zero_mat.shape)
print("dtype",zero_mat.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape (3, 4)
dtype int64


In [5]:
# Problem: How do you create a 3D tensor of shape (2, 3, 2) filled with ones?
import numpy as np
ones_tensor = np.ones((2,3,2),dtype=np.float32)
print(ones_tensor)
print("tensor shape",ones_tensor.shape)
print("data type", ones_tensor.dtype)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
tensor shape (2, 3, 2)
data type float32


In [6]:
# Problem: How do you construct a 3×3 matrix where every element is set to 7.5 ?
import numpy as np
cont_mat = np.full(shape=(3,3),fill_value=7.5)
print(cont_mat)

[[7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]]


In [7]:
# Problem: How does the arr.fill() method differ from np.full(), and how is it used to mutate an existing pre-allocated array?
import numpy as np
buf = np.empty((2,3),dtype=np.int32)
print(buf)

# Overwrite all values in-place without new memory allocation
buf.fill(99)
print(buf)

[[         0          0          0]
 [1071644672          0 1072693248]]
[[99 99 99]
 [99 99 99]]


In [8]:
# Problem: How do you generate an array of numbers from 10 to 50 with a step of 5,
# and an array with floating-point increments from 0.0 to 1.0 with a step of 0.2?

import numpy as np
int_seq = np.arange(10,50,5) # start,stop,step
print(int_seq)

float_seq = np.arange(0.0 , 1.0 , 0.2) #
print(float_seq)

[10 15 20 25 30 35 40 45]
[0.  0.2 0.4 0.6 0.8]


In [9]:
# Problem: How do you generate exactly 5 linearly spaced values between 0 and 100 (inclusive)?
import numpy as np
val = np.linspace(0,100,5)
print(val)

# (stop - start)/ num - 1

# ( 100-0 ) / 5 -1
# 100/4 = 25


[  0.  25.  50.  75. 100.]


In [10]:
# Problem: Write code that creates a 1D vector, a 2D matrix, and a 3D tensor, and display their structures.
import numpy as np
vec = np.array([1,2,3])
mat = np.array([[1,2,3],[4,5,6]])
ten = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(vec)
print(mat)
print(ten)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
#Array Properties (shape, size, ndim, dtype) # 1D or 2D and 3D
import numpy as np
vec = np.array([1,2,3])
mat = np.array([[1,2,3],[4,5,6]])
ten = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print("shape",vec.shape)
print(mat.shape)
print(ten.shape)

print("size",vec.size)
print(mat.size)
print(ten.size)

print("ndim",vec.ndim)
print(mat.ndim)
print(ten.ndim)

shape (3,)
(2, 3)
(2, 2, 2)
size 3
6
8
ndim 1
2
3


In [13]:
# Problem: Given a 2D array of shape (3, 5), what do len(arr) and arr.size return?
import numpy as np
val = np.ones((3,5))
print(val)
print(len(val)) # no. of rows
print(len(val[0])) # no. of cols

print(val.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
3
5
15


In [17]:
# indexing and slicing
# 1d array
# indexing is always start from zero and position is always start from one
import numpy as np
marks = np.array([70,80,90,85])
print(marks)
print(marks[0]) # 70
print(marks[2]) # 90
print(marks[-1]) # negative one for last value

[70 80 90 85]
70
90
85


In [22]:
# 2d array indexing
import numpy as np
students = np.array([
    [70,80,90],
    [65,75,85]
])
print(students)
# print(students[rows][cols])
print("row 0 = ",students[0])
print("row 0 and cols 0 = ",students[0][0])

[[70 80 90]
 [65 75 85]]
row 0 =  [70 80 90]
row 0 and cols 0 =  70


In [24]:
# question
import numpy as np
n =  int(input("Enter number of students:"))
names = []
marks = []

for i in range(n):
  name = input("Enter Student name:")
  mark = int(input("Enter marks:"))

  names.append(name)
  marks.append(mark)

# convert list in numpy array
names_array = np.array(names)
marks_array = np.array(marks)
print("Names:", names_array)
print("Marks:", marks_array)

Enter number of students:3
Enter Student name:nitin
Enter marks:70
Enter Student name:priyansh
Enter marks:80
Enter Student name:raj
Enter marks:90
Names: ['nitin' 'priyansh' 'raj']
Marks: [70 80 90]


In [27]:
# slicing
# 1d array
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr)
print("slicing",arr[1:3]) # starting index : end index (last value exclude)

[10 20 30 40 50 60]
slicing [20 30]


In [34]:
# basic slicing concepts
# note:- if you update slicing array then your original array also will changed
arr1 = np.array([5,6,7,9,11,2])
print(arr1)
arr1_slice = arr1[1:4]
print(arr1_slice)
print("before update index 0 of slice = ",arr1_slice[0])
arr1_slice[0] =  20
print("after update index 0 of slice = ",arr1_slice[0])

print("original array =", arr1)

[ 5  6  7  9 11  2]
[6 7 9]
before update index 0 of slice =  6
after update index 0 of slice =  20
original array = [ 5 20  7  9 11  2]


In [38]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[1:4] # last number always exclude
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[6 7 8]


In [39]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[:4] # default starting from zero index
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[5 6 7 8]


In [40]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[2:] # default last index number
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[7 8 2 3]


In [41]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[:] # default start from 0 and last index
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[5 6 7 8 2 3]


In [44]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[1:4:2] #  start from 1 and end with 3 and step by 1
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[6 8]


In [45]:
# 1d example
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[::2] #  start from 0 and end with last and step by 1
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[5 7 2]


In [47]:
# 1d example reverse
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
arr1_slice = arr1[::-1] #  start from 0 and end with last and step by -1
print(arr1)
print(arr1_slice)

[5 6 7 8 2 3]
[3 2 8 7 6 5]


In [50]:
# 1d example basic
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
print(arr1)
arr1_slice = arr1[1:4]
print("before update=",arr1_slice)

# update slice array
arr1_slice[0] = 21
print("after update=",arr1_slice)

print("original array",arr1) #

[5 6 7 8 2 3]
before update= [6 7 8]
after update= [21  7  8]
original array [ 5 21  7  8  2  3]


In [53]:
# fancy indexing for 1d
# note:- its create a new array instead of changes in original one
import numpy as np
arr1 = np.array([5,6,7,8,2,3])
print(arr1)
arr1_slice = arr1[[1,2,3]] # fancy indexing
print("before update=",arr1_slice)

# update slice array
arr1_slice[0] = 21
print("after update=",arr1_slice)

print("original array",arr1) #

[5 6 7 8 2 3]
before update= [6 7 8]
after update= [21  7  8]
original array [5 6 7 8 2 3]


In [ ]:
# boolean indexing
