In [1]:
print("helo")

helo


In [7]:
import numpy as np
list_1d = [10,20,30,40]
vec = np.array(list_1d)
print(vec)
print(vec.dtype)

# dtype
vec = np.array(list_1d,dtype=np.float16)
print(vec)
print(vec.dtype)

[10 20 30 40]
int64
[10. 20. 30. 40.]
float16


In [9]:
list_2d = [
    [1,2,3],
    [4,5,6]
]
mat = np.array(list_2d)
print(mat)
print(mat.dtype)

# dtype
mat = np.array(list_2d,dtype=np.float16)
print(mat)
print(mat.dtype)

[[1 2 3]
 [4 5 6]]
int64
[[1. 2. 3.]
 [4. 5. 6.]]
float16


In [11]:
# Problem: How do you initialize a 3×4 integer matrix populated entirely with zeros?
import numpy as np
zero_mat = np.zeros((3,4),dtype=int)
print(zero_mat)
print("shape",zero_mat.shape)
print("dtype",zero_mat.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape (3, 4)
dtype int64


In [15]:
# Problem: How do you create a 3D tensor of shape (2, 3, 2) filled with ones?
import numpy as np
ones_tensor = np.ones((2,3,2),dtype=np.float32)
print(ones_tensor)
print("tensor shape",ones_tensor.shape)
print("data type", ones_tensor.dtype)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
tensor shape (2, 3, 2)
data type float32


In [17]:
# Problem: How do you construct a 3×3 matrix where every element is set to 7.5 ?
import numpy as np
cont_mat = np.full(shape=(3,3),fill_value=7.5)
print(cont_mat)

[[7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]]


In [21]:
# Problem: How does the arr.fill() method differ from np.full(), and how is it used to mutate an existing pre-allocated array?
import numpy as np
buf = np.empty((2,3),dtype=np.int32)
print(buf)

# Overwrite all values in-place without new memory allocation
buf.fill(99)
print(buf)

[[99 99 99]
 [99 99 99]]
[[99 99 99]
 [99 99 99]]


In [24]:
# Problem: How do you generate an array of numbers from 10 to 50 with a step of 5,
# and an array with floating-point increments from 0.0 to 1.0 with a step of 0.2?

import numpy as np
int_seq = np.arange(10,50,5) # start,stop,step
print(int_seq)

float_seq = np.arange(0.0 , 1.0 , 0.2) #
print(float_seq)

[10 15 20 25 30 35 40 45]
[0.  0.2 0.4 0.6 0.8]


In [25]:
# Problem: How do you generate exactly 5 linearly spaced values between 0 and 100 (inclusive)?
import numpy as np
val = np.linspace(0,100,5)
print(val)

# (stop - start)/ num - 1

# ( 100-0 ) / 5 -1
# 100/4 = 25


[  0.  25.  50.  75. 100.]


In [30]:
# Problem: Write code that creates a 1D vector, a 2D matrix, and a 3D tensor, and display their structures.
import numpy as np
vec = np.array([1,2,3])
mat = np.array([[1,2,3],[4,5,6]])
ten = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(vec)
print(mat)
print(ten)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
#Array Properties (shape, size, ndim, dtype) # 1D or 2D and 3D
import numpy as np
vec = np.array([1,2,3])
mat = np.array([[1,2,3],[4,5,6]])
ten = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print("shape",vec.shape)
print(mat.shape)
print(ten.shape)

print("size",vec.size)
print(mat.size)
print(ten.size)

print("ndim",vec.ndim)
print(mat.ndim)
print(ten.ndim)

shape (3,)
(2, 3)
(2, 2, 2)
size 3
6
8
ndim 1
2
3


In [44]:
# Problem: Given a 2D array of shape (3, 5), what do len(arr) and arr.size return?
import numpy as np
val = np.ones((3,5))
print(val)
print(len(val)) # no. of rows
print(len(val[0])) # no. of cols

print(val.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
3
5
15
