<a href="https://colab.research.google.com/github/rajendra0968jangid/DS-ML/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

In [ ]:
import numpy as np

students = np.array([
    [101, 78, 85, 92, 88], # id,maths,english,computer,science
    [102, 65, 72, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, 60, 50],
    [105, 82, 79, 85, 80],
    [106, 55, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])

print(students)

In [ ]:
# shape,size,dimension
print("shape:",students.shape) # 10 rows, 5 cols
print("size:",students.size) # no. of elements
print("Dimensions:",students.ndim) # 2d

In [ ]:
# access single student
print(students[0]) # math , eng , com, sci

In [ ]:
# specific marks math , eng, com, sci
print(students[0,1]) # row =0 and cols =1

In [ ]:
# specific marks math col and row 3
# specific marks eng col and row 5
# specific marks com col and row 6
print(students[2,1])
print(students[4,2])
print(students[5,3])

In [ ]:
# First 3 students
print(students[:3])

In [ ]:
# Last 3 students
print(students[-3:])

In [ ]:
# First 3 students with id and math
print(students[:3,0:2]) # row , cols

In [ ]:
# extract maths
maths = students[:,1] # all rows , 1 cols
print(maths)

In [ ]:
# First 5 Students marks
print(students[:5,1:])

In [ ]:
# maths , eng, com, sci
# maths and eng
print(students[:,1:3])

In [ ]:
# com and sci
print(students[:,3:5])

In [ ]:
# reverse dataset
print(students[::-1])

In [ ]:
# reverse subject order
print(students[:,1:][:,::-1])

In [ ]:
# total | sum of marks of all subject and particular student
marks = students[:,1:]
total = np.sum(marks,axis=1) # by default row but we need cols
print(total)

# alternative
for i in range(len(marks)):
  count = 0
  for j in range(4):
    count += marks[i][j]
  print(f"student {i} marks {count}")

In [ ]:
# Average marks
marks = students[:,1:]  #

avg = np.mean(marks,axis=1) # by default row wise | for cols use axis=1
print(avg)

In [ ]:
# Calculate percentage ex. ([78 + 85 + 92 + 88]/400 * 100)
marks = students[:,1:]
per = np.sum(marks,axis=1)/400*100
print(per)


In [ ]:
# Highest and Lowest maths marks
marks = students[:,1]
min = np.min(marks)
max = np.max(marks)
print(f"minimum marks {min} and maximum marks {max}")

In [ ]:
# Average of each subject
marks = students[:,1:]
avg = np.mean(marks,axis=0)
print(avg)

In [ ]:
# maximum and minimum of each subjects
marks = students[:,1:]
min = np.max(marks,axis=0)
max = np.min(marks,axis=0)

print(min,max)

In [ ]:
# standard deviation of each subject
marks = students[:,1:]
dev = np.std(marks,axis=0)
print(dev)

In [ ]:
# np.where() | maths >= 50 -> pass another fail
marks = students[:,1]
result = np.where(marks >= 50,"Pass","Fail")
print(result)

In [ ]:
# np.where() | eng > 90 -> a grade | eng > 75 -> b grade | eng > 60 -> c grade | less then 60 fail
marks = students[:,2]
grade = np.where(marks >= 90 , "A",np.where(marks >= 75 , "B", np.where(marks >=60, "c","Fail")))

print(marks)
print(grade)

# (condition)?"true":(condition)?"true":(condition):"true":false

In [ ]:
# np.where() | 10 marks bonus | eng
marks = students[:,2]
new_marks = np.where(marks < 60, marks+10,marks)
print(new_marks)

grade = np.where(new_marks >= 90 , "A",np.where(new_marks >= 75 , "B", np.where(new_marks >=60, "c","Fail")))

print(new_marks)
print(grade)

In [ ]:
import numpy as np
students_nan = np.array([
    [101, 78, 85, 92, 88],
    [102, 65, np.nan, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, np.nan, 50],
    [105, 82, 79, 85, 80],
    [106, np.nan, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])
print(students_nan)

In [ ]:
# find nan values -> isnan()
print(np.isnan(students_nan))

In [ ]:
# count of nan values
print(np.sum(np.isnan(students_nan)))

In [ ]:
# np.where() -> find position of nan values | row and cols
result = np.where(np.isnan(students_nan))
print(result)
#
print("rows",result[0])
print("cols",result[1])

# alternative
rows,cols = np.where(np.isnan(students_nan))
print("rows",rows)
print("cols",cols)

In [ ]:
# missing values subject-wise | math , eng, com, sci
marks = students_nan[:,1:]
missing = np.sum(np.isnan(marks),axis=0)
print(missing)

In [ ]:
# replace nan with 0
cleaned = students_nan.copy()
cleaned[np.isnan(cleaned)] = 0
print(cleaned)

In [ ]:
# replace nan with subject average -> np.nanmean()
cleaned = students_nan.copy()
marks = cleaned[:,1:]
for i in range(4):
  sub = marks[:,i]
  avg = np.nanmean(sub)
  sub[np.isnan(sub)] = np.ceil(avg)

print(cleaned)

In [ ]:
# maths marks ascending and decending  -> np.sort
import numpy as np
students_nan = np.array([
    [101, 78, 85, 92, 88],
    [102, 65, np.nan, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, np.nan, 50],
    [105, 82, 79, 85, 80],
    [106, np.nan, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])
print(students_nan)

In [ ]:
maths = students_nan[:,1]
print(maths)

print(np.sort(maths)) # ascending
print(np.sort(maths)[::-1]) # decending

In [ ]:
# argsort | sort complete students by maths
# 101 , 95, 80,
# 102 , 80 , 85
# 103 , 98 , 90

# 102,80,85
# 101,95,
# 103,98,
index = np.argsort(students_nan[:,1])
print(index)
result = students_nan[index]
print(result)

# use argmin | argmax
print(np.argmin(students_nan[:,0]))

In [31]:
# vstack | hstack | delete
import numpy as np

students = np.array([
    [101, 78, 85, 92, 88], # id,maths,english,computer,science
    [102, 65, 72, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, 60, 50],
    [105, 82, 79, 85, 80],
    [106, 55, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])

print(students)

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]
 [104  45  55  60  50]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [6]:
# add new column of total -> hstack
marks = students[:,1:]
# print(marks)

total = np.sum(marks,axis=1)
# print(total)

total_column = total.reshape(-1,1)

# print(total_column)

result = np.hstack((marks,total_column))

print(result)

[[78 85 92 88]
 [65 72 70 68]
 [90 95 91 94]
 [45 55 60 50]
 [82 79 85 80]
 [55 60 58 62]
 [88 92 86 90]
 [72 68 75 70]
 [95 91 96 94]
 [40 48 45 42]]
[343 275 370 210 326 235 356 285 376 175]
[[343]
 [275]
 [370]
 [210]
 [326]
 [235]
 [356]
 [285]
 [376]
 [175]]
[[ 78  85  92  88 343]
 [ 65  72  70  68 275]
 [ 90  95  91  94 370]
 [ 45  55  60  50 210]
 [ 82  79  85  80 326]
 [ 55  60  58  62 235]
 [ 88  92  86  90 356]
 [ 72  68  75  70 285]
 [ 95  91  96  94 376]
 [ 40  48  45  42 175]]


In [ ]:
# delete -> row


In [ ]:
# delete -> column


In [27]:
# Add percentage column -> [::-1] | -> (-1,1)
marks = students[:,1:]
# print(marks)

total = np.sum(marks,axis=1)
# print(total)

# print(len(marks))
total_column = total.reshape(len(marks),1)

# print(total_column)

per = total/400*100

per_column = per.reshape(-1,1)

result = np.hstack((marks,total_column,per_column))

result = result.astype(int)
print(result)
print(result.dtype)  #

[[ 78  85  92  88 343  85]
 [ 65  72  70  68 275  68]
 [ 90  95  91  94 370  92]
 [ 45  55  60  50 210  52]
 [ 82  79  85  80 326  81]
 [ 55  60  58  62 235  58]
 [ 88  92  86  90 356  89]
 [ 72  68  75  70 285  71]
 [ 95  91  96  94 376  94]
 [ 40  48  45  42 175  43]]
int64


In [28]:
# remove computer column -> math, eng, com , sci, total , per
result = np.delete(students,4,axis=1)

print(result)

[[101  78  85  92]
 [102  65  72  70]
 [103  90  95  91]
 [104  45  55  60]
 [105  82  79  85]
 [106  55  60  58]
 [107  88  92  86]
 [108  72  68  75]
 [109  95  91  96]
 [110  40  48  45]]


In [29]:
# remove student id=104
result = np.delete(students,3,axis=0)

print(result)

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [36]:
# Find class toper
marks = students[:,1:]
print(marks)

total = np.sum(marks,axis=1)

print(total)

top_no = np.max(total)

top_index = np.argmax(total)
print(top_no,top_index)

topper = np.argmax(np.sum(marks,axis=1))
print(topper)
print(students[topper])

[[78 85 92 88]
 [65 72 70 68]
 [90 95 91 94]
 [45 55 60 50]
 [82 79 85 80]
 [55 60 58 62]
 [88 92 86 90]
 [72 68 75 70]
 [95 91 96 94]
 [40 48 45 42]]
[343 275 370 210 326 235 356 285 376 175]
376 8
8
[109  95  91  96  94]


In [49]:
# subject topper -> math , eng, com , sci
marks = students[:,1:]
print(marks)

l = ["math","eng","com","sci"]

for i in range(len(l)):
  index = np.argmax(marks[:,i])
  print(f"{l[i]} topper on index {students[index][0]}")
  print(f"marks in {l[i]} {students[index][i+1]}")


[[78 85 92 88]
 [65 72 70 68]
 [90 95 91 94]
 [45 55 60 50]
 [82 79 85 80]
 [55 60 58 62]
 [88 92 86 90]
 [72 68 75 70]
 [95 91 96 94]
 [40 48 45 42]]
math topper on index 109
marks in math 95
eng topper on index 103
marks in eng 95
com topper on index 109
marks in com 96
sci topper on index 103
marks in sci 94
