<a href="https://colab.research.google.com/github/rajendra0968jangid/DS-ML/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print("hello")

hello


In [5]:
import numpy as np

students = np.array([
    [101, 78, 85, 92, 88], # id,maths,english,computer,science
    [102, 65, 72, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, 60, 50],
    [105, 82, 79, 85, 80],
    [106, 55, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])

print(students)

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]
 [104  45  55  60  50]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [ ]:
# shape,size,dimension
print("shape:",students.shape) # 10 rows, 5 cols
print("size:",students.size) # no. of elements
print("Dimensions:",students.ndim) # 2d

shape: (10, 5)
size: 50
Dimensions: 2


In [ ]:
# access single student
print(students[0]) # math , eng , com, sci

[101  78  85  92  88]


In [ ]:
# specific marks math , eng, com, sci
print(students[0,1]) # row =0 and cols =1

78


In [ ]:
# specific marks math col and row 3
# specific marks eng col and row 5
# specific marks com col and row 6
print(students[2,1])
print(students[4,2])
print(students[5,3])

90
79
58


In [ ]:
# First 3 students
print(students[:3])

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]]


In [ ]:
# Last 3 students
print(students[-3:])

[[108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [ ]:
# First 3 students with id and math
print(students[:3,0:2]) # row , cols

[[101  78]
 [102  65]
 [103  90]]


In [ ]:
# extract maths
maths = students[:,1] # all rows , 1 cols
print(maths)

[78 65 90 45 82 55 88 72 95 40]


In [ ]:
# First 5 Students marks
print(students[:5,1:])

[[78 85 92 88]
 [65 72 70 68]
 [90 95 91 94]
 [45 55 60 50]
 [82 79 85 80]]


In [ ]:
# maths , eng, com, sci
# maths and eng
print(students[:,1:3])

[[78 85]
 [65 72]
 [90 95]
 [45 55]
 [82 79]
 [55 60]
 [88 92]
 [72 68]
 [95 91]
 [40 48]]


In [ ]:
# com and sci
print(students[:,3:5])

[[92 88]
 [70 68]
 [91 94]
 [60 50]
 [85 80]
 [58 62]
 [86 90]
 [75 70]
 [96 94]
 [45 42]]


In [ ]:
# reverse dataset
print(students[::-1])

[[110  40  48  45  42]
 [109  95  91  96  94]
 [108  72  68  75  70]
 [107  88  92  86  90]
 [106  55  60  58  62]
 [105  82  79  85  80]
 [104  45  55  60  50]
 [103  90  95  91  94]
 [102  65  72  70  68]
 [101  78  85  92  88]]


In [ ]:
# reverse subject order
print(students[:,1:][:,::-1])

[[88 92 85 78]
 [68 70 72 65]
 [94 91 95 90]
 [50 60 55 45]
 [80 85 79 82]
 [62 58 60 55]
 [90 86 92 88]
 [70 75 68 72]
 [94 96 91 95]
 [42 45 48 40]]


In [ ]:
# total | sum of marks of all subject and particular student
marks = students[:,1:]
total = np.sum(marks,axis=1) # by default row but we need cols
print(total)

# alternative
for i in range(len(marks)):
  count = 0
  for j in range(4):
    count += marks[i][j]
  print(f"student {i} marks {count}")

[343 275 370 210 326 235 356 285 376 175]
student 0 marks 343
student 1 marks 275
student 2 marks 370
student 3 marks 210
student 4 marks 326
student 5 marks 235
student 6 marks 356
student 7 marks 285
student 8 marks 376
student 9 marks 175


In [18]:
# Average marks
marks = students[:,1:]  #

avg = np.mean(marks,axis=1) # by default row wise | for cols use axis=1
print(avg)

[85.75 68.75 92.5  52.5  81.5  58.75 89.   71.25 94.   43.75]


In [21]:
# Calculate percentage ex. ([78 + 85 + 92 + 88]/400 * 100)
marks = students[:,1:]
per = np.sum(marks,axis=1)/400*100
print(per)


[85.75 68.75 92.5  52.5  81.5  58.75 89.   71.25 94.   43.75]


In [25]:
# Highest and Lowest maths marks
marks = students[:,1]
min = np.min(marks)
max = np.max(marks)
print(f"minimum marks {min} and maximum marks {max}")

minimum marks 40 and maximum marks 95


In [28]:
# Average of each subject
marks = students[:,1:]
avg = np.mean(marks,axis=0)
print(avg)

[71.  74.5 75.8 73.8]


In [30]:
# maximum and minimum of each subjects
marks = students[:,1:]
min = np.max(marks,axis=0)
max = np.min(marks,axis=0)

print(min,max)

[95 95 96 94] [40 48 45 42]


In [31]:
# standard deviation of each subject
marks = students[:,1:]
dev = np.std(marks,axis=0)
print(dev)

[18.23732437 15.71782428 16.24684585 17.56018223]


In [36]:
# np.where() | maths >= 50 -> pass another fail
marks = students[:,1]
result = np.where(marks >= 50,"Pass","Fail")
print(result)

['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail']


In [38]:
# np.where() | eng > 90 -> a grade | eng > 75 -> b grade | eng > 60 -> c grade | less then 60 fail
marks = students[:,2]
grade = np.where(marks >= 90 , "A",np.where(marks >= 75 , "B", np.where(marks >=60, "c","Fail")))

print(marks)
print(grade)

# (condition)?"true":(condition)?"true":(condition):"true":false

[85 72 95 55 79 60 92 68 91 48]
['B' 'c' 'A' 'Fail' 'B' 'c' 'A' 'c' 'A' 'Fail']


In [41]:
# np.where() | 10 marks bonus | eng
marks = students[:,2]
new_marks = np.where(marks < 60, marks+10,marks)
print(new_marks)

grade = np.where(new_marks >= 90 , "A",np.where(new_marks >= 75 , "B", np.where(new_marks >=60, "c","Fail")))

print(new_marks)
print(grade)

[85 72 95 65 79 60 92 68 91 58]
[85 72 95 65 79 60 92 68 91 58]
['B' 'c' 'A' 'c' 'B' 'c' 'A' 'c' 'A' 'Fail']
