<a href="https://colab.research.google.com/github/rajendra0968jangid/DS-ML/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
print("hello")

hello


In [33]:
import numpy as np

students = np.array([
    [101, 78, 85, 92, 88], # id,maths,english,computer,science
    [102, 65, 72, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, 60, 50],
    [105, 82, 79, 85, 80],
    [106, 55, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])

print(students)

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]
 [104  45  55  60  50]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [34]:
# shape,size,dimension
print("shape:",students.shape) # 10 rows, 5 cols
print("size:",students.size) # no. of elements
print("Dimensions:",students.ndim) # 2d

shape: (10, 5)
size: 50
Dimensions: 2


In [35]:
# access single student
print(students[0]) # math , eng , com, sci

[101  78  85  92  88]


In [36]:
# specific marks math
print(students[0,3]) # row =0 and cols =1

92


In [37]:
# specific marks math col and row 3
# specific marks eng col and row 5
# specific marks com col and row 6
print(students[2,1])
print(students[4,2])
print(students[5,3])
# specific marks stu_id col and row 7
# print(students[row,cols])
print(students[6,0])

90
79
58
107


In [38]:
# First 3 students -> 1 TO 3
print(students[0:3]) # -> 0 , 1 , 2

# get students from 4 to 8 -> 0 , 1 , 2 ,3 , 4 , 5 , 6 , 7 , 8
print(students[3:8])

# get students from 5 to 8 only math cols
print(students[4:8,1])

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]]
[[104  45  55  60  50]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]]
[82 55 88 72]


In [39]:
# Last 3 students
print(students[-3:])

[[108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [40]:
# First 3 students with id and math
print(students[:3,0:2]) # row , cols

[[101  78]
 [102  65]
 [103  90]]


In [41]:
# extract maths
maths = students[:,1] # all rows , 1 cols
print(maths)

[78 65 90 45 82 55 88 72 95 40]


In [42]:
# First 5 Students marks
print(students[:5,1:])

[[78 85 92 88]
 [65 72 70 68]
 [90 95 91 94]
 [45 55 60 50]
 [82 79 85 80]]


In [43]:
# maths , eng, com, sci
# maths and eng
print(students[:,1:3])

[[78 85]
 [65 72]
 [90 95]
 [45 55]
 [82 79]
 [55 60]
 [88 92]
 [72 68]
 [95 91]
 [40 48]]


In [44]:
# com and sci
print(students[:,3:5])

[[92 88]
 [70 68]
 [91 94]
 [60 50]
 [85 80]
 [58 62]
 [86 90]
 [75 70]
 [96 94]
 [45 42]]


In [45]:
# reverse dataset
print(students[::-1])

[[110  40  48  45  42]
 [109  95  91  96  94]
 [108  72  68  75  70]
 [107  88  92  86  90]
 [106  55  60  58  62]
 [105  82  79  85  80]
 [104  45  55  60  50]
 [103  90  95  91  94]
 [102  65  72  70  68]
 [101  78  85  92  88]]


In [46]:
# reverse subject order
print(students[:,1:][:,::-1])

[[88 92 85 78]
 [68 70 72 65]
 [94 91 95 90]
 [50 60 55 45]
 [80 85 79 82]
 [62 58 60 55]
 [90 86 92 88]
 [70 75 68 72]
 [94 96 91 95]
 [42 45 48 40]]


In [47]:
# total | sum of marks of all subject and particular student
marks = students[:,1:]
total = np.sum(marks,axis=1) # by default row but we need cols
print(total)

# alternative
for i in range(len(marks)):
  count = 0
  for j in range(4):
    count += marks[i][j]
  print(f"student {i} marks {count}")

[343 275 370 210 326 235 356 285 376 175]
student 0 marks 343
student 1 marks 275
student 2 marks 370
student 3 marks 210
student 4 marks 326
student 5 marks 235
student 6 marks 356
student 7 marks 285
student 8 marks 376
student 9 marks 175


In [48]:
# Average marks
marks = students[:,1:]  #

avg = np.mean(marks,axis=1) # by default row wise | for cols use axis=1
print(avg)

[85.75 68.75 92.5  52.5  81.5  58.75 89.   71.25 94.   43.75]


In [49]:
# Calculate percentage ex. ([78 + 85 + 92 + 88]/400 * 100)
marks = students[:,1:]
per = np.sum(marks,axis=1)/400*100
print(per)


[85.75 68.75 92.5  52.5  81.5  58.75 89.   71.25 94.   43.75]


In [50]:
# Highest and Lowest maths marks
marks = students[:,1]
min = np.min(marks)
max = np.max(marks)
print(f"minimum marks {min} and maximum marks {max}")

minimum marks 40 and maximum marks 95


In [51]:
# Average of each subject
marks = students[:,1:]
avg = np.mean(marks,axis=0)
print(avg)

[71.  74.5 75.8 73.8]


In [52]:
# maximum and minimum of each subjects
marks = students[:,1:]
min = np.max(marks,axis=0)
max = np.min(marks,axis=0)

print(min,max)

[95 95 96 94] [40 48 45 42]


In [53]:
# standard deviation of each subject
marks = students[:,1:]
dev = np.std(marks,axis=0)
print(dev)

[18.23732437 15.71782428 16.24684585 17.56018223]


In [54]:
# np.where() | maths >= 50 -> pass another fail
marks = students[:,1]
result = np.where(marks >= 50,"Pass","Fail")
print(result)

['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail']


In [55]:
# np.where() | eng > 90 -> a grade | eng > 75 -> b grade | eng > 60 -> c grade | less then 60 fail
marks = students[:,2]
grade = np.where(marks >= 90 , "A",np.where(marks >= 75 , "B", np.where(marks >=60, "c","Fail")))

print(marks)
print(grade)

# (condition)?"true":(condition)?"true":(condition):"true":false

[85 72 95 55 79 60 92 68 91 48]
['B' 'c' 'A' 'Fail' 'B' 'c' 'A' 'c' 'A' 'Fail']


In [56]:
# np.where() | 10 marks bonus | eng
marks = students[:,2]
new_marks = np.where(marks < 60, marks+10,marks)
print(new_marks)

grade = np.where(new_marks >= 90 , "A",np.where(new_marks >= 75 , "B", np.where(new_marks >=60, "c","Fail")))

print(new_marks)
print(grade)

[85 72 95 65 79 60 92 68 91 58]
[85 72 95 65 79 60 92 68 91 58]
['B' 'c' 'A' 'c' 'B' 'c' 'A' 'c' 'A' 'Fail']


In [57]:
import numpy as np
students_nan = np.array([
    [101, 78, 85, 92, 88],
    [102, 65, np.nan, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, np.nan, 50],
    [105, 82, 79, 85, 80],
    [106, np.nan, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])
print(students_nan)

[[101.  78.  85.  92.  88.]
 [102.  65.  nan  70.  68.]
 [103.  90.  95.  91.  94.]
 [104.  45.  55.  nan  50.]
 [105.  82.  79.  85.  80.]
 [106.  nan  60.  58.  62.]
 [107.  88.  92.  86.  90.]
 [108.  72.  68.  75.  70.]
 [109.  95.  91.  96.  94.]
 [110.  40.  48.  45.  42.]]


In [58]:
# find nan values -> isnan()
print(np.isnan(students_nan))

[[False False False False False]
 [False False  True False False]
 [False False False False False]
 [False False False  True False]
 [False False False False False]
 [False  True False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [59]:
# count of nan values
print(np.sum(np.isnan(students_nan)))

3


In [60]:
# np.where() -> find position of nan values | row and cols
result = np.where(np.isnan(students_nan))
print(result)
#
print("rows",result[0])
print("cols",result[1])

# alternative
rows,cols = np.where(np.isnan(students_nan))
print("rows",rows)
print("cols",cols)

(array([1, 3, 5]), array([2, 3, 1]))
rows [1 3 5]
cols [2 3 1]
rows [1 3 5]
cols [2 3 1]


In [61]:
# missing values subject-wise | math , eng, com, sci
marks = students_nan[:,1:]
missing = np.sum(np.isnan(marks),axis=0)
print(missing)

[1 1 1 0]


In [62]:
# replace nan with 0
cleaned = students_nan.copy()
cleaned[np.isnan(cleaned)] = 0
print(cleaned)

[[101.  78.  85.  92.  88.]
 [102.  65.   0.  70.  68.]
 [103.  90.  95.  91.  94.]
 [104.  45.  55.   0.  50.]
 [105.  82.  79.  85.  80.]
 [106.   0.  60.  58.  62.]
 [107.  88.  92.  86.  90.]
 [108.  72.  68.  75.  70.]
 [109.  95.  91.  96.  94.]
 [110.  40.  48.  45.  42.]]


In [63]:
# replace nan with subject average -> np.nanmean()
cleaned = students_nan.copy()
marks = cleaned[:,1:]
for i in range(4):
  sub = marks[:,i]
  avg = np.nanmean(sub)
  sub[np.isnan(sub)] = np.ceil(avg)

print(cleaned)

[[101.  78.  85.  92.  88.]
 [102.  65.  75.  70.  68.]
 [103.  90.  95.  91.  94.]
 [104.  45.  55.  78.  50.]
 [105.  82.  79.  85.  80.]
 [106.  73.  60.  58.  62.]
 [107.  88.  92.  86.  90.]
 [108.  72.  68.  75.  70.]
 [109.  95.  91.  96.  94.]
 [110.  40.  48.  45.  42.]]


In [64]:
# maths marks ascending and decending  -> np.sort
import numpy as np
students_nan = np.array([
    [101, 78, 85, 92, 88],
    [102, 65, np.nan, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, np.nan, 50],
    [105, 82, 79, 85, 80],
    [106, np.nan, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])
print(students_nan)

[[101.  78.  85.  92.  88.]
 [102.  65.  nan  70.  68.]
 [103.  90.  95.  91.  94.]
 [104.  45.  55.  nan  50.]
 [105.  82.  79.  85.  80.]
 [106.  nan  60.  58.  62.]
 [107.  88.  92.  86.  90.]
 [108.  72.  68.  75.  70.]
 [109.  95.  91.  96.  94.]
 [110.  40.  48.  45.  42.]]


In [65]:
maths = students_nan[:,1]
print(maths)

print(np.sort(maths)) # ascending
print(np.sort(maths)[::-1]) # decending

[78. 65. 90. 45. 82. nan 88. 72. 95. 40.]
[40. 45. 65. 72. 78. 82. 88. 90. 95. nan]
[nan 95. 90. 88. 82. 78. 72. 65. 45. 40.]


In [66]:
# argsort | sort complete students by maths
# 101 , 95, 80,
# 102 , 80 , 85
# 103 , 98 , 90

# 102,80,85
# 101,95,
# 103,98,
index = np.argsort(students_nan[:,1])
print(index)
result = students_nan[index]
print(result)

# use argmin | argmax
print(np.argmin(students_nan[:,0]))

[9 3 1 7 0 4 6 2 8 5]
[[110.  40.  48.  45.  42.]
 [104.  45.  55.  nan  50.]
 [102.  65.  nan  70.  68.]
 [108.  72.  68.  75.  70.]
 [101.  78.  85.  92.  88.]
 [105.  82.  79.  85.  80.]
 [107.  88.  92.  86.  90.]
 [103.  90.  95.  91.  94.]
 [109.  95.  91.  96.  94.]
 [106.  nan  60.  58.  62.]]
0


In [67]:
# vstack | hstack | delete
import numpy as np

students = np.array([
    [101, 78, 85, 92, 88], # id,maths,english,computer,science
    [102, 65, 72, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, 60, 50],
    [105, 82, 79, 85, 80],
    [106, 55, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])

print(students)

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]
 [104  45  55  60  50]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [68]:
# add new column of total -> hstack
marks = students[:,1:]
# print(marks)

total = np.sum(marks,axis=1)
# print(total)

total_column = total.reshape(-1,1)

# print(total_column)

result = np.hstack((marks,total_column))

print(result)

[[ 78  85  92  88 343]
 [ 65  72  70  68 275]
 [ 90  95  91  94 370]
 [ 45  55  60  50 210]
 [ 82  79  85  80 326]
 [ 55  60  58  62 235]
 [ 88  92  86  90 356]
 [ 72  68  75  70 285]
 [ 95  91  96  94 376]
 [ 40  48  45  42 175]]


In [69]:
# delete -> row


In [70]:
# delete -> column


In [71]:
# Add percentage column -> [::-1] | -> (-1,1)
marks = students[:,1:]
# print(marks)

total = np.sum(marks,axis=1)
# print(total)

# print(len(marks))
total_column = total.reshape(len(marks),1)

# print(total_column)

per = total/400*100

per_column = per.reshape(-1,1)

result = np.hstack((marks,total_column,per_column))

result = result.astype(int)
print(result)
print(result.dtype)  #

[[ 78  85  92  88 343  85]
 [ 65  72  70  68 275  68]
 [ 90  95  91  94 370  92]
 [ 45  55  60  50 210  52]
 [ 82  79  85  80 326  81]
 [ 55  60  58  62 235  58]
 [ 88  92  86  90 356  89]
 [ 72  68  75  70 285  71]
 [ 95  91  96  94 376  94]
 [ 40  48  45  42 175  43]]
int64


In [72]:
# remove computer column -> math, eng, com , sci, total , per
result = np.delete(students,4,axis=1)

print(result)

[[101  78  85  92]
 [102  65  72  70]
 [103  90  95  91]
 [104  45  55  60]
 [105  82  79  85]
 [106  55  60  58]
 [107  88  92  86]
 [108  72  68  75]
 [109  95  91  96]
 [110  40  48  45]]


In [73]:
# remove student id=104
result = np.delete(students,3,axis=0)

print(result)

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [74]:
# Find class toper
marks = students[:,1:]
print(marks)

total = np.sum(marks,axis=1)

print(total)

top_no = np.max(total)

top_index = np.argmax(total)
print(top_no,top_index)

topper = np.argmax(np.sum(marks,axis=1))
print(topper)
print(students[topper])

[[78 85 92 88]
 [65 72 70 68]
 [90 95 91 94]
 [45 55 60 50]
 [82 79 85 80]
 [55 60 58 62]
 [88 92 86 90]
 [72 68 75 70]
 [95 91 96 94]
 [40 48 45 42]]
[343 275 370 210 326 235 356 285 376 175]
376 8
8
[109  95  91  96  94]


In [75]:
# subject topper -> math , eng, com , sci
marks = students[:,1:]
print(marks)

l = ["math","eng","com","sci"]

for i in range(len(l)):
  index = np.argmax(marks[:,i])
  print(f"{l[i]} topper on index {students[index][0]}")
  print(f"marks in {l[i]} {students[index][i+1]}")


[[78 85 92 88]
 [65 72 70 68]
 [90 95 91 94]
 [45 55 60 50]
 [82 79 85 80]
 [55 60 58 62]
 [88 92 86 90]
 [72 68 75 70]
 [95 91 96 94]
 [40 48 45 42]]
math topper on index 109
marks in math 95
eng topper on index 103
marks in eng 95
com topper on index 109
marks in com 96
sci topper on index 103
marks in sci 94
